using System.Windows.Forms;
using Bolsover.Shortcuts.Model;
using Bolsover.Shortcuts.Utils;
using Bolsover.Shortcuts.View;

namespace Bolsover.Shortcuts.Presenter
{
    public class KeyboardPresenter
    {
        private readonly KeyboardControl _view;
        public KeyText _keyText = new();

        public KeyboardPresenter(KeyboardControl view)
        {
            _view = view;
            SetupLatexImages();
            ClearDefaultText();
            DoDataBindings();
            
        }
        
        private void DoDataBinding(Control key, string keyTextName)
        {
            key.DataBindings.Add(new Binding("Text", _keyText, keyTextName, true, DataSourceUpdateMode.OnPropertyChanged));
        }
        
        private void DoDataBindings()
        {
            DoDataBinding(_view.F1Key, "F1KeyText");
            DoDataBinding(_view.F2Key, "F2KeyText");
            DoDataBinding(_view.F3Key, "F3KeyText");
            DoDataBinding(_view.F4Key, "F4KeyText");
            DoDataBinding(_view.F5Key, "F5KeyText");
            DoDataBinding(_view.F6Key, "F6KeyText");
            DoDataBinding(_view.F7Key, "F7KeyText");
            DoDataBinding(_view.F8Key, "F8KeyText");
            DoDataBinding(_view.F9Key, "F9KeyText");
            DoDataBinding(_view.F10Key, "F10KeyText");
            DoDataBinding(_view.F11Key, "F11KeyText");
            DoDataBinding(_view.F12Key, "F12KeyText");
            DoDataBinding(_view.AKey, "AKeyText");
            DoDataBinding(_view.BKey, "BKeyText");
            DoDataBinding(_view.CKey, "CKeyText");
            DoDataBinding(_view.DKey, "DKeyText");
            DoDataBinding(_view.EKey, "EKeyText");
            DoDataBinding(_view.FKey, "FKeyText");
            DoDataBinding(_view.GKey, "GKeyText");
            DoDataBinding(_view.HKey, "HKeyText");
            DoDataBinding(_view.IKey, "IKeyText");
            DoDataBinding(_view.JKey, "JKeyText");
            DoDataBinding(_view.KKey, "KKeyText");
            DoDataBinding(_view.LKey, "LKeyText");
            DoDataBinding(_view.MKey, "MKeyText");
            DoDataBinding(_view.NKey, "NKeyText");
            DoDataBinding(_view.OKey, "OKeyText");
            DoDataBinding(_view.PKey, "PKeyText");
            DoDataBinding(_view.QKey, "QKeyText");
            DoDataBinding(_view.RKey, "RKeyText");
            DoDataBinding(_view.SKey, "SKeyText");
            DoDataBinding(_view.TKey, "TKeyText");
            DoDataBinding(_view.UKey, "UKeyText");
            DoDataBinding(_view.VKey, "VKeyText");
            DoDataBinding(_view.WKey, "WKeyText");
            DoDataBinding(_view.XKey, "XKeyText");
            DoDataBinding(_view.YKey, "YKeyText");
            DoDataBinding(_view.ZKey, "ZKeyText");
            DoDataBinding(_view.ZeroKey, "ZeroKeyText");
            DoDataBinding(_view.OneKey, "OneKeyText");
            DoDataBinding(_view.TwoKey, "TwoKeyText");
            DoDataBinding(_view.ThreeKey, "ThreeKeyText");
            DoDataBinding(_view.FourKey, "FourKeyText");
            DoDataBinding(_view.FiveKey, "FiveKeyText");
            DoDataBinding(_view.SixKey, "SixKeyText");
            DoDataBinding(_view.SevenKey, "SevenKeyText");
            DoDataBinding(_view.EightKey, "EightKeyText");
            DoDataBinding(_view.NineKey, "NineKeyText");
            DoDataBinding(_view.SpaceKey, "SpaceKeyText");
            DoDataBinding(_view.TabKey, "TabKeyText");
            DoDataBinding(_view.EnterKey, "EnterKeyText");
            DoDataBinding(_view.BackspaceKey, "BackspaceKeyText");
            DoDataBinding(_view.EscapeKey, "EscapeKeyText");
            DoDataBinding(_view.LeftShiftKey, "LeftShiftKeyText");
            DoDataBinding(_view.RightShiftKey, "RightShiftKeyText");
            DoDataBinding(_view.LeftCtrlKey, "LeftCtrlKeyText");
            DoDataBinding(_view.RightCtrlKey, "RightCtrlKeyText");
            DoDataBinding(_view.LeftAltKey, "LeftAltKeyText");
            DoDataBinding(_view.AltGrKey, "AltGrKeyText");
            DoDataBinding(_view.InsertKey, "InsertKeyText");
            DoDataBinding(_view.HomeKey, "HomeKeyText");
            DoDataBinding(_view.EndKey, "EndKeyText");
            DoDataBinding(_view.PageUpKey, "PageUpKeyText");
            DoDataBinding(_view.PageDownKey, "PageDownKeyText");
            DoDataBinding(_view.UpKey, "UpKeyText");
            DoDataBinding(_view.DownKey, "DownKeyText");
            DoDataBinding(_view.LeftKey, "LeftKeyText");
            DoDataBinding(_view.RightKey, "RightKeyText");
            DoDataBinding(_view.NumLockKey, "NumLockKeyText");
            DoDataBinding(_view.Num0Key, "Num0KeyText");
            DoDataBinding(_view.Num1Key, "Num1KeyText");
            DoDataBinding(_view.Num2Key, "Num2KeyText");
            DoDataBinding(_view.Num3Key, "Num3KeyText");
            DoDataBinding(_view.Num4Key, "Num4KeyText");
            DoDataBinding(_view.Num5Key, "Num5KeyText");
            DoDataBinding(_view.Num6Key, "Num6KeyText");
            DoDataBinding(_view.Num7Key, "Num7KeyText");
            DoDataBinding(_view.Num8Key, "Num8KeyText");
            DoDataBinding(_view.Num9Key, "Num9KeyText");
            DoDataBinding(_view.NumPlusKey, "NumPlusKeyText");
            DoDataBinding(_view.NumMinusKey, "NumMinusKeyText");
            DoDataBinding(_view.NumMultiplyKey, "NumMultiplyKeyText");
            DoDataBinding(_view.NumDivideKey, "NumDivideKeyText");
            DoDataBinding(_view.NumDecimalKey, "NumDecimalKeyText");
            DoDataBinding(_view.NumEnterKey, "NumEnterKeyText");
            DoDataBinding(_view.DeleteKey, "DeleteKeyText");
            DoDataBinding(_view.PrintScreenKey, "PrintScreenKeyText");
            DoDataBinding(_view.PauseBreakKey, "PauseBreakKeyText");
            DoDataBinding(_view.ScrollLockKey, "ScrollLockKeyText");
            DoDataBinding(_view.CapsLockKey, "CapsLockKeyText");
            DoDataBinding(_view.GraveKey, "GraveKeyText");
            DoDataBinding(_view.MinusKey, "MinusKeyText");
            DoDataBinding(_view.EqualKey, "EqualKeyText");
            DoDataBinding(_view.BackslashKey, "BackslashKeyText");
            DoDataBinding(_view.LeftBracketKey, "LeftBracketKeyText");
            DoDataBinding(_view.RightBracketKey, "RightBracketKeyText");
            DoDataBinding(_view.SemicolonKey, "SemicolonKeyText");
            DoDataBinding(_view.ApostropheKey, "ApostropheKeyText");
            DoDataBinding(_view.CommaKey, "CommaKeyText");
            DoDataBinding(_view.PeriodKey, "PeriodKeyText");
            DoDataBinding(_view.SlashKey, "SlashKeyText");
            DoDataBinding(_view.HashKey, "HashKeyText");
            DoDataBinding(_view.WindowKey, "WindowKeyText");
            DoDataBinding(_view.FnKey, "FnKeyText");
        }
        
        private void ClearDefaultText()
        {
            _view.F1Key.Text = "";
            _view.F2Key.Text = "";
            _view.F3Key.Text = "";
            _view.F4Key.Text = "";
            _view.F5Key.Text = "";
            _view.F6Key.Text = "";
            _view.F7Key.Text = "";
            _view.F8Key.Text = "";
            _view.F9Key.Text = "";
            _view.F10Key.Text = "";
            _view.F11Key.Text = "";
            _view.F12Key.Text = "";
            _view.AKey.Text = "";
            _view.BKey.Text = "";
            _view.CKey.Text = "";
            _view.DKey.Text = "";
            _view.EKey.Text = "";
            _view.FKey.Text = "";
            _view.GKey.Text = "";
            _view.HKey.Text = "";
            _view.IKey.Text = "";
            _view.JKey.Text = "";
            _view.KKey.Text = "";
            _view.LKey.Text = "";
            _view.MKey.Text = "";
            _view.NKey.Text = "";
            _view.OKey.Text = "";
            _view.PKey.Text = "";
            _view.QKey.Text = "";
            _view.RKey.Text = "";
            _view.SKey.Text = "";
            _view.TKey.Text = "";
            _view.UKey.Text = "";
            _view.VKey.Text = "";
            _view.WKey.Text = "";
            _view.XKey.Text = "";
            _view.YKey.Text = "";
            _view.ZKey.Text = "";
            _view.ZeroKey.Text = "";
            _view.OneKey.Text = "";
            _view.TwoKey.Text = "";
            _view.ThreeKey.Text = "";
            _view.FourKey.Text = "";
            _view.FiveKey.Text = "";
            _view.SixKey.Text = "";
            _view.SevenKey.Text = "";
            _view.EightKey.Text = "";
            _view.NineKey.Text = "";
            _view.SpaceKey.Text = "";
            _view.TabKey.Text = "";
            _view.EnterKey.Text = "";
            _view.BackspaceKey.Text = "";
            _view.EscapeKey.Text = "";
            _view.LeftShiftKey.Text = "";
            _view.RightShiftKey.Text = "";
            _view.LeftCtrlKey.Text = "";
            _view.RightCtrlKey.Text = "";
            _view.LeftAltKey.Text = "";
            _view.AltGrKey.Text = "";
            _view.InsertKey.Text = "";
            _view.HomeKey.Text = "";
            _view.EndKey.Text = "";
            _view.PageUpKey.Text = "";
            _view.PageDownKey.Text = "";
            _view.UpKey.Text = "";
            _view.DownKey.Text = "";
            _view.LeftKey.Text = "";
            _view.RightKey.Text = "";
            _view.NumLockKey.Text = "";
            _view.Num0Key.Text = "";
            _view.Num1Key.Text = "";
            _view.Num2Key.Text = "";
            _view.Num3Key.Text = "";
            _view.Num4Key.Text = "";
            _view.Num5Key.Text = "";
            _view.Num6Key.Text = "";
            _view.Num7Key.Text = "";
            _view.Num8Key.Text = "";
            _view.Num9Key.Text = "";
            _view.NumPlusKey.Text = "";
            _view.NumMinusKey.Text = "";
            _view.NumMultiplyKey.Text = "";
            _view.NumDivideKey.Text = "";
            _view.NumDecimalKey.Text = "";
            _view.NumEnterKey.Text = "";
            _view.DeleteKey.Text = "";
            _view.PrintScreenKey.Text = "";
            _view.PauseBreakKey.Text = "";
            _view.ScrollLockKey.Text = "";
            _view.CapsLockKey.Text = "";
            _view.GraveKey.Text = "";
            _view.MinusKey.Text = "";
            _view.EqualKey.Text = "";
            _view.BackslashKey.Text = "";
            _view.LeftBracketKey.Text = "";
            _view.RightBracketKey.Text = "";
            _view.SemicolonKey.Text = "";
            _view.ApostropheKey.Text = "";
            _view.CommaKey.Text = "";
            _view.PeriodKey.Text = "";
            _view.SlashKey.Text = "";
            _view.HashKey.Text = "";
            _view.WindowKey.Text = "";
            _view.FnKey.Text = "";
        }
        
        private void SetupLatexImages()
        { 
            _view.F1Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.F1);
           _view.F2Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.F2);
           _view.F3Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.F3);
           _view.F4Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.F4);
           _view.F5Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.F5);
           _view.F6Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.F6);
           _view.F7Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.F7);
           _view.F8Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.F8);
           _view.F9Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.F9);
           _view.F10Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.F10);
           _view.F11Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.F11);
           _view.F12Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.F12);
           _view.AKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.A);
           _view.BKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.B);
           _view.CKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.C);
           _view.DKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.D);
           _view.EKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.E);
           _view.FKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.F);
           _view.GKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.G);
           _view.HKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.H);
           _view.IKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.I);
           _view.JKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.J);
           _view.KKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.K);
           _view.LKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.L);
           _view.MKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.M);
           _view.NKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.N);
           _view.OKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.O);
           _view.PKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.P);
           _view.QKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Q);
           _view.RKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.R);
           _view.SKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.S);
           _view.TKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.T);
           _view.UKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.U);
           _view.VKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.V);
           _view.WKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.W);
           _view.XKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.X);
           _view.YKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Y);
           _view.ZKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Z);
           _view.ZeroKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Zero);
           _view.OneKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.One);
           _view.TwoKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Two);
           _view.ThreeKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Three);
           _view.FourKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Four);
           _view.FiveKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Five);
           _view.SixKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Six);
           _view.SevenKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Seven);
           _view.EightKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Eight);
           _view.NineKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Nine);
           _view.SpaceKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Space);
           _view.TabKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Tab);
           _view.EnterKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Enter);
           _view.BackspaceKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Backspace);
           _view.EscapeKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Escape);
           _view.LeftShiftKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.LeftShift);
           _view.RightShiftKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.RightShift);
           _view.LeftCtrlKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.LeftCtrl);
           _view.RightCtrlKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.RightCtrl);
           _view.LeftAltKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.LeftAlt);
           _view.AltGrKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.AltGr);
           _view.DeleteKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Delete);
           _view.InsertKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Insert);
           _view.HomeKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Home);
           _view.EndKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.End);
           _view.PageUpKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.PageUp);
           _view.PageDownKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.PageDown);
           _view.UpKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Up);
           _view.DownKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Down);
           _view.LeftKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Left);
           _view.RightKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Right);
           _view.NumLockKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumLock);
           _view.Num0Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPad0);
           _view.Num1Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPad1);
           _view.Num2Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPad2);
           _view.Num3Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPad3);
           _view.Num4Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPad4);
           _view.Num5Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPad5);
           _view.Num6Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPad6);
           _view.Num7Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPad7);
           _view.Num8Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPad8);
           _view.Num9Key.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPad9);
           _view.NumPlusKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPadPlus);
           _view.NumMinusKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPadMinus);
           _view.NumMultiplyKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPadMultiply);
           _view.NumDivideKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPadDivide);
           _view.NumDecimalKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPadDecimal);
           _view.NumEnterKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.NumPadEnter);
           _view.PrintScreenKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.PrintScreen);
           _view.PauseBreakKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.PauseBreak);
           _view.ScrollLockKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.ScrollLock);
           _view.CapsLockKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.CapsLock);
           _view.GraveKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Grave);
           _view.MinusKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Minus);
           _view.EqualKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Equal);
           _view.BackslashKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Backslash);
           _view.LeftBracketKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.LeftBracket);
           _view.RightBracketKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.RightBracket);
           _view.SemicolonKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Semicolon);
           _view.ApostropheKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Apostrophe);
           _view.CommaKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Comma);
           _view.PeriodKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Period);
           _view.SlashKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Slash);
           _view.HashKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Hash);
           _view.WindowKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Win);
           _view.FnKey.Image = LatexUtils.CreateImageFromLatex(LatexStrings.Fn);
        }
    }
}